### ISSUE TITLE
Couldn't use `Import` module in my codebase

### ISSUE THREAD

**Issue by k0va1** [dry-rb/dry-system#119]
I have `Import = Container.injector` in my `import.rb`. And when I tried to create my own namespace with `Import` module, I've got an error `Import is not a module`
```ruby
module Import
  module Parsers
    class SpeakersParser < Operation
      #...
    end
  end
end
```
Is it any possible solutions not to rename one of `Import`s?

**Comment by timriley** [comment]
`Import = Container.injector` assigns an _object_ to `Import`. It's not a module, which is why you're getting that error.

The solution here would be to:

(1) rename your app's `Import` namespacing module to something else, or
(2) assign the injector object to another constant, e.g. `Inject = Container.injector`

**Comment by k0va1** [comment]
@timriley thanks!
