### ISSUE TITLE
Remove method_missing behavior from bootable component lifecycle DSL

### ISSUE THREAD

**Issue by timriley** [dry-rb/dry-system#164]
Particularly these bits:

```ruby
      def method_missing(meth, *args, &block)
        if target.registered?(meth)
          target[meth]
        elsif container.key?(meth)
          container[meth]
```

There's too much magic in this behavior, and the concision it may add doesn't outweigh just how much harder it makes it to understand the behavior within the bootable component lifecycle blocks.

**Comment by solnic** [comment]
@timriley so with your recent improvements we can basically assume that the intermediate container is no longer needed, right? If that's true then I'd say we should change DSL so that it doesn't do instance_eval anymore and simply call lifecycle blocks with the main evaluation context.

**Comment by timriley** [comment]
@solnic The biggest related outcome of my recent improvements was the improved consistence of lazy component resolution, so if dealing with that was one of the reasons the intermediate container existed, then yes, that would definitely help.

I did file a separate issue about removing the intermediate container (https://github.com/dry-rb/dry-system/issues/165), and my thinking in doing so was mostly about how it made things more confusing to users than it should be. If we can get away with the bootable component lifecycle code interacting directly with the main container, then it means things will be much simpler to understand!

**Comment by solnic** [comment]
@timriley sorry but I just remembered that the intermediate container is *probably* something we need for external component providers. Maybe we can easily make it work w/o it though...did you consider this? I also remember you had some ideas how it should be improved so maybe it's something I could work on before 1.0 assuming it's not too much 🙂

**Comment by timriley** [comment]
This is good to know, thanks @solnic! We'll have to have a go at removing the intermediate containers and see what exactly breaks with external component providers. And yeah, I did remember having _some_ kind of thoughts about improving the component providers too, but I'll need to get my head back in the space before I potentially remember what they were! 😅

**Comment by solnic** [comment]
@timriley I just had a quick look to see why we have this lifecycle container and there are two things that are tricky:

* It makes it possible to handle `:namespace` option which is very handy. See [here](https://github.com/dry-rb/dry-system/blob/d01c78cf68c05a1ab71356b739f9a35bae52e6a1/lib/dry/system/components/bootable.rb#L266)
* It *captures* configuration via intermediate config. See [here](https://github.com/dry-rb/dry-system/blob/d01c78cf68c05a1ab71356b739f9a35bae52e6a1/lib/dry/system/lifecycle.rb#L66) - now I believe this is precisely because `configure` is a trigger so I couldn't use it directly with the target container...

I *think* this is how it could be solved:

* When `namespace` option is used, we simply do `container.namespaced` and yield that into the block, ie `Lifecycle.new(..., container.namespaced(inferred_namespace_name)`
* Since plugins use `before(:configure)` to add their own settings, or `after(:configure)` to register their own objects, we can't just allow using settings within lifecycle blocks as it's going to trigger plugins, which is *not* what we want. That's why we need to (finally) move away from abusing configure 😅 A pub/sub-based setup process works great in rom and we probably want to have the same thing here

**Comment by timriley** [comment]
@solnic I think I might tackle this sometime very soon, so if you have any further thoughts about that last dot point of yours, I'd definitely love to hear it!

Particularly, on this:

> we can't just allow using settings within lifecycle blocks as it's going to trigger plugins, which is not what we want

Do you have examples of how you're seeing this currently done, and how it'd make things go badly if we did away with this intermediary container?

**Comment by solnic** [comment]
@timriley I think the best way is to try to remove it and see what happens with the spec suite and a couple of existing apps that we have. I'll triple-check it once you open a PR.

**Comment by timriley** [comment]
In the end I decided to keep this behaviour in the #202 provider overhaul. Feels useful enough and we've made the code evaluation context much clearer thanks to the class-backed providers.
