### ISSUE TITLE
Zeitwerk::Registry is private interface

### ISSUE THREAD

**Issue by fxn** [dry-rb/dry-system#259]
Hi!

The [`Zeitwerk::Registry`](https://github.com/fxn/zeitwerk/blob/main/lib/zeitwerk/registry.rb) class is private interface. It is undocumented, and its internal interface is marked as `@private` all over the place for more stress.

I am going to rename those methods to enforce stricter rules, but wanted to understand the use case you have [here](https://github.com/dry-rb/dry-system/blob/605abd9e1f9f4c399cba0993e117e58799563bd1/spec/support/zeitwerk_helpers.rb) before doing that. Maybe it is suggesting there's a missing need.

The reason `Zeitwerk::Registry.loaders` is private has different levels. On one hand, Zeitwerk does not expose any of its internal collections directly. For example, you have `push_dir` as a method, you don't mutate a collection. The public API boundary is the one that guarantees the internal state is consistent. This is a generic public interface guideline.

However, the main point in the case of `loaders` is that gem loaders are, generally speaking, not the business of anyone else. You should not even know they exist, the way a gem loads is generally private, you just know you only need to `require` their entrypoint.

Those loaders must be protected by design, because gems must have full control over their own (unless their loaders belong to their public interface, you know).

For example, the only way to broadcast things to the registered loaders are the documented blessed ones like `Zeitwerk::Loader.eager_load`. Even then, you don't access the registry externally.

Could it be the case that you are missing a collection of loaders you control? Like, you may instantiate loaders, register them in a global collection of yours, and those are the ones you need to act upon?

**Comment by timriley** [comment]
@fxn Thanks for checking in on this. Having seen your tweets on the matter, I would of course prefer to use public Zeitwerk APIs wherever possible, so I hope a conversation here can help us find a better approach for dry-system, or help inform future adjustments to Zeitwerk's public API :)

(BTW, everything I write here also applies to our approach for managing Zeitwerk loaders inside [hanami/hanami](https://github.com/hanami/hanami), so whatever we learn/change from this conversation, I can also do inside that repository)

So, in our test suite we have various integration specs that create files in tmp directories to mimic working dry-system-based applications, and then run tests over the resulting code.  Here's one example: [spec/integration/container/plugins/zeitwerk/namespaces_spec.rb](https://github.com/dry-rb/dry-system/blob/c9d51d7f7e86a4de7eca986d90f950c9dd11b61f/spec/integration/container/plugins/zeitwerk/namespaces_spec.rb)

Because we reuse the same few Ruby module names in each of these tests, we have helpers to clean up those constants as they represent state we do not  want to leak into other tests. See our [spec/support/loaded_constants_cleaning.rb](https://github.com/dry-rb/dry-system/blob/c9d51d7f7e86a4de7eca986d90f950c9dd11b61f/spec/support/loaded_constants_cleaning.rb) as an example of this.

Zeitwerk's loaders represent another piece of state we want to clean up, especially since their autoloads would be referring to now-absent files and constants.

To do this, I originally repurposed code I found in test/support/loader_test, since what we were looking to achieve in our tests was similar to the function of the code in that file.

This is why the code is as it is today. You can note that we've made it as minimally invasive as possible by only touching loaders that manage files inside our own /spec/ directory, or directories under `Dir.tmpdir`.

You do have a point about "missing a collection of loaders [we] control." We could probably achieve the same ends as our current teardown_zeitwerk helper by finding some way to hold a reference to each Zeitwerk loader that may be created over the course of a test. Then we could teardown those loaders only, without touching the global `Zeitwerk::Registry.loaders`.

I can look into doing this, but it would likely need to be towards the end of the year or the beginning of next. I am working absolutely flat out to release Hanami 2.0 right now, and then to prepare a talk about it to present in December. I'm happy to do this work, of course, but I just want to understand what your plans are in the meantime regarding access to `Registry.loaders`.

Thank you, @fxn! I've greatly enjoyed working with Zeitwerk, and what it's made possible for our libraries and frameworks! ❤️

**Comment by fxn** [comment]
@timriley Is `teardown_zeitwerk` a helper used by the suite of the project, not exposed to users?

**Comment by timriley** [comment]
@fxn That's right, it's internal to the test suite (it's defined in `spec/support/zeitwerk_helpers.rb` after all), and **not exposed in any way** to users via our published gems.

**Comment by fxn** [comment]
@timriley Fantastic! So we are in control.

Conceptually, I don't want to normalize the concept of having all loaders available and `loaders` is going to be gone in this set of patches I am writing to enforce privacy to private interfaces. As I explained above, intuitively I prefer to protect the loaders by design.

Not "protect" in the sense of making them unavailable to abuse, because in Ruby that's just not possible. I mean that the API makes you think "scoped to what I control" and keeps a barrier to the idea that you can iterate and deal with all the loaders, because other loaders are non of your business.

An idea that I have been pondering for a while, seeing new use cases, is that of "groups" of loaders. That would allow client projects to have the collection available without having to write this support themselves.

And I believe this could be provided in a lightweight manner with a feature that already exists: tags. So, we could have APIs like

```ruby
Zeitwerk::Loader.eager_load_namespace(MyFramework, tag: "my-framework.*")
```

or

```ruby
Zeitwerk::Loader.get_all_by_tag(/\A(dry-system|custom_loader)\z/).each do |loader|
  loader.unregister
end
```

Would that kind of solution make sense for this test suite and the one of Hanami?

Then we might need to talk about `unregister` and about those constants that the test suite unload by hand. But let's go with this one first.

**Comment by fxn** [comment]
Nah, I am not sure this interface accomplishes what I pursuit, because the mental cost to a glob pattern `"*"` is almost nothing.
