### ISSUE TITLE
In tests cannot resolve anything from container

### ISSUE THREAD

**Issue by davidpelaez** [dry-rb/dry-system#32]
In my `spec_helper.rb` I require my `boot.rb` and I finalize the app:

``` ruby
require File.expand_path("../../boot", __FILE__)
require "dry/container/stub"
Application.enable_stubs!
Application.finalize!
```

In a test I keep getting: `RuntimeError: can't modify frozen #<Class:Application>`:

``` ruby
require 'spec_helper'

describe :sandbox_authorization do
  it 'should fail' do
    result = Application['operations.sandbox_authorization'].call true
    expect(result).to be(false)
  end
end
```

Should I _not_ `finalize!` the app? How do I get all my app for testing then? I thought about booting but I don't know how I'd mix booting with auto registered folders. If I have to put constantly `use` to load all other parts of the system I don't understand what's the use. I think I'm missing how to use this gem and had to remove it for a while because I literally was unable to make testing work with either Rspec or Minitest :( Can you let me knkow what I'm missing or if there's a bug somewhere or both?

**Comment by solnic** [comment]
You should only `finalize!` for full-stack tests (ie capybara specs etc.). For tests that don't need the whole app to be loaded simply use a separate spec_helper. This is how I've done it in a couple of projects and it works very well. There are way to make this experience better though, ie we could provide an rspec plugin for setting things up more easily, although I'm not sure if it's worth the effort.

Re stubbing, you need to do it inside your specs, and make sure it gets disabled after specs finished, because if you're running your whole test suite it will affect all tests. This is a global setting so needs to be reset.

I'll add a section about this to the docs...soon ;)

**Comment by davidpelaez** [comment]
What do you mean by separate spec_helpers @solnic ? manually requiring every single file? We have for instance a folder with `app/operations` and they're autoregistered, I don't know how to load all operations and handle registration. If I don't finalize, auto registered folders don't get registered. I don't understand how to load a single part when auto registration is involved basically.

**Comment by davidpelaez** [comment]
Maybe something like `Application.auto_register! 'app/operations'` in `operations_spec_helper.rb`? So that I explicitly load the parts that I want auto registered and `Import` would handle loading of the dependencies?

**Comment by timriley** [comment]
I'm pretty sure @solnic means something like this: having a `spec/spec_helper.rb` that doesn't finalize anything at all, and a `spec/app_helper.rb` that finalizes everything. Then, only in your integration tests would you `require "app_helper"`. This means your unit tests only use the base spec_helper, which doesn't do the finalization, and then lazily loads any dependencies when you auto-inject them.

There's a hitch though: right now, this _won't_ work if you try and resolve dependencies directly from the container (i.e. not via the auto-injector), which is what you're doing in your example code above. We need to fix #33 before this happens.

However, if you're unit testing a class, I'd recommend you instantiate that class directly rather than pulling it from your app's container. Could you do something like this?

```ruby
subject(:authorization) { Operations::SandboxAuthorization.new }

# then in your spec example
result = authorization.call true
expect(result).to be(false)
```

**Comment by davidpelaez** [comment]
Thanks for the help @timriley I think I didn't understand it. I'm confused as to when to use the container. Should I think about it only as an intermideate tool to do requires, autoregistration and for the dependency injection to work? Maybe I don't get the intention of the `Application` container and when to use it and when not to. 

Right now I use dry-system for auto-registration with objects that I use for dependency injection and also to have a simple wildcard require like `Application.require 'lib/resources/**/*.rb'` without using another gem like 'require_all'. This alone helps, but I feel like and downplaying the benefits of the container or maybe it's the wrong point of view! In general I think that the sample Rodakase app and the simple standalone examples don't resolve some more complex use cases like mine. Could you elaborate a little more as to when to look something up in the container and when to use the constant names directly?

**Comment by solnic** [comment]
Currently stubbing is not gonna work for a finalized container, since it's frozen so we can't modify it. I guess we should disable freezing when env is test.

> Maybe I don't get the intention of the Application container and when to use it and when not to. (..) Could you elaborate a little more as to when to look something up in the container and when to use the constant names directly?

Don't use a container in unit tests, where you can easily just pass mocks to a constructor. Do use it in integration tests (feature, controller, api, request whatever you want to call them :)) because in such tests you shouldn't care about details like object instantiation, and if you need to stub something, you can do it with `enable_stubs` feature (although we do need to disable freezing in test env first, PR is coming).

> I think that the sample Rodakase app and the simple standalone examples don't resolve some more complex use cases like mine

Berg is a pretty good example, it's a multi-app setup, got separated spec helpers etc.

**Comment by solnic** [comment]
Closing in favor of #49
