### ISSUE TITLE
How `stop` callback is invoked?

### ISSUE THREAD

**Issue by mainameiz** [dry-rb/dry-system#90]
Consider following example from documentation

```
Application.finalize(:persistence) do |container|
  start do
    require 'sequel'
    container.register('persistence.db', Sequel.connect(ENV['DB_URL']))
  end

  stop do
    db.disconnect
  end
end
```

When `stop` callback (which calls `db.disconnect`) will be called? Is there a method to *stop* all components at once (like `finalize!` which *starts* all components)

This case is not covered in documentation...

**Comment by GustavoCaso** [comment]
So, looks like at the container level there is no method for `stopping` a specific component. 
We have `start` and `init` from the container level https://github.com/dry-rb/dry-system/blob/master/lib/dry/system/container.rb#L321-L342 maybe would be interesting to add `stop`, I do not know how would work after `finalize!` since everything is `freeze`.

Why do you want to call `stop` in your application?

**Comment by mainameiz** [comment]
> Why do you want to call stop in your application?

I'm using cloud service to monitor exceptions (https://www.honeybadger.io). It is using async queue to send messages, so when my service is shutting down I want to make sure this async queue will be cleared.

**Comment by mainameiz** [comment]
I found [an example](https://github.com/dry-rb/dry-system/blob/master/spec/unit/container/boot_spec.rb#L50) of stopping one component but it would be great to have more common method to stop all components at once.

As my colleague mention, this feature would require to have some sort of DSL to declare stop order of components (opposing to `use` keyword).

**Comment by solnic** [comment]
Stopping components is not fully finished. We need a corresponding `stop` method in `Container`, just like Gustavo mentioned. We could also consider something like `Container.shutdown`, that would go through all booted components and stop them.
