### ISSUE TITLE
Support conditional booting of providers

### ISSUE THREAD

**Issue by davydovanton** [dry-rb/dry-system#94]
I found the interesting case for improvement.

In my hanami app I have server and rake "instances". For rake I need to use `aws` dependency but in server booting, I don't need it. In this case, it will be better for me to load `aws` only for rake env.

In hanami I can use `Hanami.app?(:rake)` ([docs](http://hanamirb.org/guides/1.2/projects/selectively-boot-apps/)). And it looks like this:

```ruby
if Hanami.app?(:rake)
  Container.boot :rake_test do |container|
    start do
      container.register :rake_test, Object.new
    end
  end
end
```

Also, I updated rakefile:

```ruby
ENV['HANAMI_APPS'] = 'rake'
```

----------------------------

So, what I suggest. Create a optional argument for booting dependency, something like this:

```ruby
Container.boot(:rake_test, condition: -> { Hanami.app?(:rake) }) do |container|
  start do
    container.register :rake_test, Object.new
  end
end
```

And in this case, dry-system will boot dependency only with `true` in condition. Also, it can be related to https://github.com/dry-rb/dry-system/issues/73 but I'm not sure. 

WDYT?

cc @solnic @timriley @GustavoCaso

**Comment by timriley** [comment]
@davydovanton I like this idea. 👍 

And your suggested implementation is generic enough such that it would also e.g. Hanami to come in and provide a more framework-specific API to wrap it and set that `condition:` proc as required.

(For similar scenarios in our apps we've designed our rake tasks so that they never fully boot the container, instead only booting specific components as required. This works fine if all those bootable components are _also_ needed when fully booting the container (i.e. to run the web app), but it wouldn't fit in the situation you describe, where you need a bootable component for specific tasks that should _not_ always boot when the full container boots.)

My only other thought here is (of course) about naming. I wonder whether `when:` or `boot_if:` or something might be a better name for the option.

**Comment by GustavoCaso** [comment]
@davydovanton I also like the idea 🎉 

 As @timriley mentioned is generic enough.

I do not have an example as to how we do it in our apps 😢.

And regarding naming, I think it reads really well:

```ruby
Container.boot(:rake_test, when: -> { Hanami.app?(:rake) }) do |container|
  start do
    container.register :rake_test, Object.new
  end
end
```

I'm not sure if `when` being a ruby keyword would became a problem ❓

**Comment by jodosha** [comment]
👍 We will need it for Hanami, if we integrate with `dry-system` as boot engine. See https://github.com/hanami/hanami/blob/master/lib/hanami/components/components.rb#L88

**Comment by davydovanton** [comment]
thanks for the feedback!

I have more than one example when it can be useful. In one project we use different apps in one repository (like in hanami or old umbrella in dry-web). In one admin application, we need to use LDAP auth. But instead of loading this dependency for each app we can load it only for specific.

Or another example, we have web app and kafka consumer app in one project. We don't need to boot kafka instance to web app. With this, we can easily disable booting unnecessary dependencies.

About naming. I agree that `condition` is really strange name :D

:+1: for `when` here :clap:

**Comment by solnic** [comment]
I wanted to add this feature too 😄

**Comment by davydovanton** [comment]
Folks, I created a PR with this logic. Could you check it?

**Comment by v-kolesnikov** [comment]
What is the disadvantage of using simple `if` statement? It is a more clear and straightforward way for the most cases like manage environments, different behaviour for Rake tasks etc. For the more complex cases, like different components for the different apps - it is possible (already now) to separate them into the different system-containers. Why not?
